### ISSUE TITLE
，，，

### ISSUE THREAD

**Issue by jp1017** [java-aodeng/hope#1]
`𝓢𝓹𝓻𝓲𝓷𝓰 𝓑𝓸𝓸𝓽-𝓢𝓹𝓻𝓲𝓷𝓰 𝓒𝓵𝓸𝓾𝓭学习笔记art` 怎么输入的呢？

**Comment by java-aodeng** [comment]
https://gitmoji.carloscuesta.me/  gitmoji表情哦
